// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.12.4
// source: inputevent.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Kind int32

const (
	Kind_Outlier Kind = 0
	Kind_New     Kind = 1
	Kind_Old     Kind = 2
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "Outlier",
		1: "New",
		2: "Old",
	}
	Kind_value = map[string]int32{
		"Outlier": 0,
		"New":     1,
		"Old":     2,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_inputevent_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_inputevent_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{0}
}

type RoomVersion int32

const (
	RoomVersion_V1 RoomVersion = 0
	RoomVersion_V2 RoomVersion = 1
	RoomVersion_V3 RoomVersion = 2
	RoomVersion_V4 RoomVersion = 3
	RoomVersion_V5 RoomVersion = 4
	RoomVersion_V6 RoomVersion = 5
)

// Enum value maps for RoomVersion.
var (
	RoomVersion_name = map[int32]string{
		0: "V1",
		1: "V2",
		2: "V3",
		3: "V4",
		4: "V5",
		5: "V6",
	}
	RoomVersion_value = map[string]int32{
		"V1": 0,
		"V2": 1,
		"V3": 2,
		"V4": 3,
		"V5": 4,
		"V6": 5,
	}
)

func (x RoomVersion) Enum() *RoomVersion {
	p := new(RoomVersion)
	*p = x
	return p
}

func (x RoomVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_inputevent_proto_enumTypes[1].Descriptor()
}

func (RoomVersion) Type() protoreflect.EnumType {
	return &file_inputevent_proto_enumTypes[1]
}

func (x RoomVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomVersion.Descriptor instead.
func (RoomVersion) EnumDescriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{1}
}

type InputRoomEvents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomEvents []*RoomEvent `protobuf:"bytes,1,rep,name=RoomEvents,proto3" json:"RoomEvents,omitempty"`
}

func (x *InputRoomEvents) Reset() {
	*x = InputRoomEvents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InputRoomEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRoomEvents) ProtoMessage() {}

func (x *InputRoomEvents) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRoomEvents.ProtoReflect.Descriptor instead.
func (*InputRoomEvents) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{0}
}

func (x *InputRoomEvents) GetRoomEvents() []*RoomEvent {
	if x != nil {
		return x.RoomEvents
	}
	return nil
}

type RoomEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          Kind           `protobuf:"varint,1,opt,name=Kind,proto3,enum=proto.Kind" json:"Kind,omitempty"`
	Event         *HeaderedEvent `protobuf:"bytes,2,opt,name=Event,proto3" json:"Event,omitempty"`
	AuthEventIDs  []string       `protobuf:"bytes,3,rep,name=AuthEventIDs,proto3" json:"AuthEventIDs,omitempty"`
	HasState      bool           `protobuf:"varint,4,opt,name=HasState,proto3" json:"HasState,omitempty"`
	StateEventIDs []string       `protobuf:"bytes,5,rep,name=StateEventIDs,proto3" json:"StateEventIDs,omitempty"`
	SendAsServer  string         `protobuf:"bytes,6,opt,name=SendAsServer,proto3" json:"SendAsServer,omitempty"`
	TransactionID *TransactionID `protobuf:"bytes,7,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{1}
}

func (x *RoomEvent) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_Outlier
}

func (x *RoomEvent) GetEvent() *HeaderedEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RoomEvent) GetAuthEventIDs() []string {
	if x != nil {
		return x.AuthEventIDs
	}
	return nil
}

func (x *RoomEvent) GetHasState() bool {
	if x != nil {
		return x.HasState
	}
	return false
}

func (x *RoomEvent) GetStateEventIDs() []string {
	if x != nil {
		return x.StateEventIDs
	}
	return nil
}

func (x *RoomEvent) GetSendAsServer() string {
	if x != nil {
		return x.SendAsServer
	}
	return ""
}

func (x *RoomEvent) GetTransactionID() *TransactionID {
	if x != nil {
		return x.TransactionID
	}
	return nil
}

type TransactionID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID     int64  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	TransactionID string `protobuf:"bytes,2,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
}

func (x *TransactionID) Reset() {
	*x = TransactionID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionID) ProtoMessage() {}

func (x *TransactionID) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionID.ProtoReflect.Descriptor instead.
func (*TransactionID) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionID) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *TransactionID) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

type HeaderedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventHeader *EventHeader `protobuf:"bytes,1,opt,name=EventHeader,proto3" json:"EventHeader,omitempty"`
}

func (x *HeaderedEvent) Reset() {
	*x = HeaderedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeaderedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderedEvent) ProtoMessage() {}

func (x *HeaderedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderedEvent.ProtoReflect.Descriptor instead.
func (*HeaderedEvent) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderedEvent) GetEventHeader() *EventHeader {
	if x != nil {
		return x.EventHeader
	}
	return nil
}

type EventHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomVersion RoomVersion `protobuf:"varint,1,opt,name=RoomVersion,proto3,enum=proto.RoomVersion" json:"RoomVersion,omitempty"`
}

func (x *EventHeader) Reset() {
	*x = EventHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHeader) ProtoMessage() {}

func (x *EventHeader) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHeader.ProtoReflect.Descriptor instead.
func (*EventHeader) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{4}
}

func (x *EventHeader) GetRoomVersion() RoomVersion {
	if x != nil {
		return x.RoomVersion
	}
	return RoomVersion_V1
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Redacted  bool   `protobuf:"varint,1,opt,name=Redacted,proto3" json:"Redacted,omitempty"`
	EventJSON []byte `protobuf:"bytes,2,opt,name=EventJSON,proto3" json:"EventJSON,omitempty"`
	// Types that are assignable to Fields:
	//	*Event_EventV1
	//	*Event_EventV2
	Fields      isEvent_Fields `protobuf_oneof:"fields"`
	RoomVersion RoomVersion    `protobuf:"varint,3,opt,name=RoomVersion,proto3,enum=proto.RoomVersion" json:"RoomVersion,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetRedacted() bool {
	if x != nil {
		return x.Redacted
	}
	return false
}

func (x *Event) GetEventJSON() []byte {
	if x != nil {
		return x.EventJSON
	}
	return nil
}

func (m *Event) GetFields() isEvent_Fields {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (x *Event) GetEventV1() *EventV1 {
	if x, ok := x.GetFields().(*Event_EventV1); ok {
		return x.EventV1
	}
	return nil
}

func (x *Event) GetEventV2() *EventV2 {
	if x, ok := x.GetFields().(*Event_EventV2); ok {
		return x.EventV2
	}
	return nil
}

func (x *Event) GetRoomVersion() RoomVersion {
	if x != nil {
		return x.RoomVersion
	}
	return RoomVersion_V1
}

type isEvent_Fields interface {
	isEvent_Fields()
}

type Event_EventV1 struct {
	EventV1 *EventV1 `protobuf:"bytes,4,opt,name=EventV1,proto3,oneof"`
}

type Event_EventV2 struct {
	EventV2 *EventV2 `protobuf:"bytes,5,opt,name=EventV2,proto3,oneof"`
}

func (*Event_EventV1) isEvent_Fields() {}

func (*Event_EventV2) isEvent_Fields() {}

type EventV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventFields *EventFields      `protobuf:"bytes,1,opt,name=EventFields,proto3" json:"EventFields,omitempty"`
	PrevEvents  []*EventReference `protobuf:"bytes,2,rep,name=PrevEvents,proto3" json:"PrevEvents,omitempty"`
	AuthEvents  []*EventReference `protobuf:"bytes,3,rep,name=AuthEvents,proto3" json:"AuthEvents,omitempty"`
}

func (x *EventV1) Reset() {
	*x = EventV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventV1) ProtoMessage() {}

func (x *EventV1) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventV1.ProtoReflect.Descriptor instead.
func (*EventV1) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{6}
}

func (x *EventV1) GetEventFields() *EventFields {
	if x != nil {
		return x.EventFields
	}
	return nil
}

func (x *EventV1) GetPrevEvents() []*EventReference {
	if x != nil {
		return x.PrevEvents
	}
	return nil
}

func (x *EventV1) GetAuthEvents() []*EventReference {
	if x != nil {
		return x.AuthEvents
	}
	return nil
}

type EventV2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventFields *EventFields `protobuf:"bytes,1,opt,name=EventFields,proto3" json:"EventFields,omitempty"`
	PrevEvents  []string     `protobuf:"bytes,2,rep,name=PrevEvents,proto3" json:"PrevEvents,omitempty"`
	AuthEvents  []string     `protobuf:"bytes,3,rep,name=AuthEvents,proto3" json:"AuthEvents,omitempty"`
}

func (x *EventV2) Reset() {
	*x = EventV2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventV2) ProtoMessage() {}

func (x *EventV2) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventV2.ProtoReflect.Descriptor instead.
func (*EventV2) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{7}
}

func (x *EventV2) GetEventFields() *EventFields {
	if x != nil {
		return x.EventFields
	}
	return nil
}

func (x *EventV2) GetPrevEvents() []string {
	if x != nil {
		return x.PrevEvents
	}
	return nil
}

func (x *EventV2) GetAuthEvents() []string {
	if x != nil {
		return x.AuthEvents
	}
	return nil
}

type EventReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventID     string `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	EventSHA256 []byte `protobuf:"bytes,2,opt,name=EventSHA256,proto3" json:"EventSHA256,omitempty"`
}

func (x *EventReference) Reset() {
	*x = EventReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReference) ProtoMessage() {}

func (x *EventReference) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReference.ProtoReflect.Descriptor instead.
func (*EventReference) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{8}
}

func (x *EventReference) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *EventReference) GetEventSHA256() []byte {
	if x != nil {
		return x.EventSHA256
	}
	return nil
}

type EventFields struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventID        string               `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	RoomID         string               `protobuf:"bytes,2,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	Sender         string               `protobuf:"bytes,3,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Type           string               `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	StateKey       string               `protobuf:"bytes,5,opt,name=StateKey,proto3" json:"StateKey,omitempty"` // optional ?
	RawJSON        []byte               `protobuf:"bytes,6,opt,name=RawJSON,proto3" json:"RawJSON,omitempty"`
	Redacts        string               `protobuf:"bytes,7,opt,name=Redacts,proto3" json:"Redacts,omitempty"`
	Depth          int64                `protobuf:"varint,8,opt,name=Depth,proto3" json:"Depth,omitempty"`
	Unsigned       []byte               `protobuf:"bytes,9,opt,name=Unsigned,proto3" json:"Unsigned,omitempty"`
	OriginServerTS *timestamp.Timestamp `protobuf:"bytes,10,opt,name=OriginServerTS,proto3" json:"OriginServerTS,omitempty"`
	Origin         string               `protobuf:"bytes,11,opt,name=Origin,proto3" json:"Origin,omitempty"`
}

func (x *EventFields) Reset() {
	*x = EventFields{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inputevent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFields) ProtoMessage() {}

func (x *EventFields) ProtoReflect() protoreflect.Message {
	mi := &file_inputevent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFields.ProtoReflect.Descriptor instead.
func (*EventFields) Descriptor() ([]byte, []int) {
	return file_inputevent_proto_rawDescGZIP(), []int{9}
}

func (x *EventFields) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *EventFields) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

func (x *EventFields) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *EventFields) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventFields) GetStateKey() string {
	if x != nil {
		return x.StateKey
	}
	return ""
}

func (x *EventFields) GetRawJSON() []byte {
	if x != nil {
		return x.RawJSON
	}
	return nil
}

func (x *EventFields) GetRedacts() string {
	if x != nil {
		return x.Redacts
	}
	return ""
}

func (x *EventFields) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *EventFields) GetUnsigned() []byte {
	if x != nil {
		return x.Unsigned
	}
	return nil
}

func (x *EventFields) GetOriginServerTS() *timestamp.Timestamp {
	if x != nil {
		return x.OriginServerTS
	}
	return nil
}

func (x *EventFields) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

var File_inputevent_proto protoreflect.FileDescriptor

var file_inputevent_proto_rawDesc = []byte{
	0x0a, 0x10, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x0f, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x30, 0x0a,
	0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x0a, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x9e, 0x02, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x2a,
	0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x65, 0x64, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x75,
	0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0c, 0x41, 0x75, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x48, 0x61, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x48, 0x61, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x22, 0x53, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x44, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x45, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x65,
	0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x0b,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0b, 0x52,
	0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xd9, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52,
	0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x52,
	0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x4a, 0x53, 0x4f, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4a, 0x53, 0x4f, 0x4e, 0x12, 0x2a, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x31,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x48, 0x00, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56,
	0x31, 0x12, 0x2a, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x32, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x56, 0x32, 0x48, 0x00, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x32, 0x12, 0x34, 0x0a,
	0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xad, 0x01,
	0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x31, 0x12, 0x34, 0x0a, 0x0b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x52, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x35, 0x0a, 0x0a, 0x50, 0x72, 0x65, 0x76, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0a, 0x50, 0x72, 0x65, 0x76,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x7f, 0x0a,
	0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x32, 0x12, 0x34, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x52, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x50, 0x72, 0x65, 0x76, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x50, 0x72, 0x65, 0x76, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x4c,
	0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x48, 0x41, 0x32, 0x35, 0x36, 0x22, 0xc9, 0x02, 0x0a,
	0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x61, 0x77, 0x4a, 0x53, 0x4f,
	0x4e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x52, 0x61, 0x77, 0x4a, 0x53, 0x4f, 0x4e,
	0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x52, 0x65, 0x64, 0x61, 0x63, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x65,
	0x70, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x44, 0x65, 0x70, 0x74, 0x68,
	0x12, 0x1a, 0x0a, 0x08, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x0e,
	0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x53, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0e, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x2a, 0x25, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x6c, 0x69, 0x65, 0x72, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x03, 0x4e, 0x65, 0x77, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x6c, 0x64, 0x10, 0x02, 0x2a,
	0x3d, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x06,
	0x0a, 0x02, 0x56, 0x31, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x32, 0x10, 0x01, 0x12, 0x06,
	0x0a, 0x02, 0x56, 0x33, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x34, 0x10, 0x03, 0x12, 0x06,
	0x0a, 0x02, 0x56, 0x35, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x36, 0x10, 0x05, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_inputevent_proto_rawDescOnce sync.Once
	file_inputevent_proto_rawDescData = file_inputevent_proto_rawDesc
)

func file_inputevent_proto_rawDescGZIP() []byte {
	file_inputevent_proto_rawDescOnce.Do(func() {
		file_inputevent_proto_rawDescData = protoimpl.X.CompressGZIP(file_inputevent_proto_rawDescData)
	})
	return file_inputevent_proto_rawDescData
}

var file_inputevent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_inputevent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inputevent_proto_goTypes = []interface{}{
	(Kind)(0),                   // 0: proto.Kind
	(RoomVersion)(0),            // 1: proto.RoomVersion
	(*InputRoomEvents)(nil),     // 2: proto.InputRoomEvents
	(*RoomEvent)(nil),           // 3: proto.RoomEvent
	(*TransactionID)(nil),       // 4: proto.TransactionID
	(*HeaderedEvent)(nil),       // 5: proto.HeaderedEvent
	(*EventHeader)(nil),         // 6: proto.EventHeader
	(*Event)(nil),               // 7: proto.Event
	(*EventV1)(nil),             // 8: proto.EventV1
	(*EventV2)(nil),             // 9: proto.EventV2
	(*EventReference)(nil),      // 10: proto.EventReference
	(*EventFields)(nil),         // 11: proto.eventFields
	(*timestamp.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_inputevent_proto_depIdxs = []int32{
	3,  // 0: proto.InputRoomEvents.RoomEvents:type_name -> proto.RoomEvent
	0,  // 1: proto.RoomEvent.Kind:type_name -> proto.Kind
	5,  // 2: proto.RoomEvent.Event:type_name -> proto.HeaderedEvent
	4,  // 3: proto.RoomEvent.TransactionID:type_name -> proto.TransactionID
	6,  // 4: proto.HeaderedEvent.EventHeader:type_name -> proto.EventHeader
	1,  // 5: proto.EventHeader.RoomVersion:type_name -> proto.RoomVersion
	8,  // 6: proto.Event.EventV1:type_name -> proto.EventV1
	9,  // 7: proto.Event.EventV2:type_name -> proto.EventV2
	1,  // 8: proto.Event.RoomVersion:type_name -> proto.RoomVersion
	11, // 9: proto.EventV1.EventFields:type_name -> proto.eventFields
	10, // 10: proto.EventV1.PrevEvents:type_name -> proto.EventReference
	10, // 11: proto.EventV1.AuthEvents:type_name -> proto.EventReference
	11, // 12: proto.EventV2.EventFields:type_name -> proto.eventFields
	12, // 13: proto.eventFields.OriginServerTS:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_inputevent_proto_init() }
func file_inputevent_proto_init() {
	if File_inputevent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inputevent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InputRoomEvents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeaderedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventV2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inputevent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFields); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_inputevent_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Event_EventV1)(nil),
		(*Event_EventV2)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inputevent_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inputevent_proto_goTypes,
		DependencyIndexes: file_inputevent_proto_depIdxs,
		EnumInfos:         file_inputevent_proto_enumTypes,
		MessageInfos:      file_inputevent_proto_msgTypes,
	}.Build()
	File_inputevent_proto = out.File
	file_inputevent_proto_rawDesc = nil
	file_inputevent_proto_goTypes = nil
	file_inputevent_proto_depIdxs = nil
}
