// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.12.4
// source: roomversion.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoomVersion int32

const (
	RoomVersion_UNKNOWN RoomVersion = 0
	RoomVersion_V1      RoomVersion = 1
	RoomVersion_V2      RoomVersion = 2
	RoomVersion_V3      RoomVersion = 3
	RoomVersion_V4      RoomVersion = 4
	RoomVersion_V5      RoomVersion = 5
	RoomVersion_V6      RoomVersion = 6
)

// Enum value maps for RoomVersion.
var (
	RoomVersion_name = map[int32]string{
		0: "UNKNOWN",
		1: "V1",
		2: "V2",
		3: "V3",
		4: "V4",
		5: "V5",
		6: "V6",
	}
	RoomVersion_value = map[string]int32{
		"UNKNOWN": 0,
		"V1":      1,
		"V2":      2,
		"V3":      3,
		"V4":      4,
		"V5":      5,
		"V6":      6,
	}
)

func (x RoomVersion) Enum() *RoomVersion {
	p := new(RoomVersion)
	*p = x
	return p
}

func (x RoomVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_roomversion_proto_enumTypes[0].Descriptor()
}

func (RoomVersion) Type() protoreflect.EnumType {
	return &file_roomversion_proto_enumTypes[0]
}

func (x RoomVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomVersion.Descriptor instead.
func (RoomVersion) EnumDescriptor() ([]byte, []int) {
	return file_roomversion_proto_rawDescGZIP(), []int{0}
}

var File_roomversion_proto protoreflect.FileDescriptor

var file_roomversion_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x6f, 0x6f, 0x6d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x4a, 0x0a, 0x0b, 0x52,
	0x6f, 0x6f, 0x6d, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x31, 0x10, 0x01, 0x12,
	0x06, 0x0a, 0x02, 0x56, 0x32, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x33, 0x10, 0x03, 0x12,
	0x06, 0x0a, 0x02, 0x56, 0x34, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x56, 0x35, 0x10, 0x05, 0x12,
	0x06, 0x0a, 0x02, 0x56, 0x36, 0x10, 0x06, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roomversion_proto_rawDescOnce sync.Once
	file_roomversion_proto_rawDescData = file_roomversion_proto_rawDesc
)

func file_roomversion_proto_rawDescGZIP() []byte {
	file_roomversion_proto_rawDescOnce.Do(func() {
		file_roomversion_proto_rawDescData = protoimpl.X.CompressGZIP(file_roomversion_proto_rawDescData)
	})
	return file_roomversion_proto_rawDescData
}

var file_roomversion_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_roomversion_proto_goTypes = []interface{}{
	(RoomVersion)(0), // 0: common.RoomVersion
}
var file_roomversion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_roomversion_proto_init() }
func file_roomversion_proto_init() {
	if File_roomversion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roomversion_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roomversion_proto_goTypes,
		DependencyIndexes: file_roomversion_proto_depIdxs,
		EnumInfos:         file_roomversion_proto_enumTypes,
	}.Build()
	File_roomversion_proto = out.File
	file_roomversion_proto_rawDesc = nil
	file_roomversion_proto_goTypes = nil
	file_roomversion_proto_depIdxs = nil
}
